# Generated by Django 5.1.5 on 2025-01-22 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('passport_number', models.CharField(max_length=50)),
                ('mark_for_deletion', models.BooleanField(default=False)),
                ('not_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.IntegerField(choices=[(0, 'Тип 0'), (1, 'Тип 1')])),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client_city', models.CharField(max_length=100)),
                ('clients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bd.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=100)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.airlines')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hotel', models.CharField(max_length=200)),
                ('child_menu', models.BooleanField(default=False)),
                ('have_nanny', models.BooleanField(default=False)),
                ('child_program', models.BooleanField(default=False)),
                ('hotel_address', models.TextField()),
                ('geo_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.clients')),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.managers')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.contracts')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.paymentmethods')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.paymentstatuses')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=200)),
                ('mark_for_deletion', models.BooleanField(default=False)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.cities')),
                ('flights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.flights')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.hotels')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_excursion', models.CharField(max_length=200)),
                ('night_transfer', models.BooleanField(default=False)),
                ('danger_level', models.IntegerField(default=0)),
                ('child_friendly', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.cities')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.organizations')),
                ('tours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd.tours')),
            ],
        ),
        migrations.AddField(
            model_name='contracts',
            name='tours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd.tours'),
        ),
    ]
